station_list = [
    'Aircraft',
    'Alamein',
    'Albion',
    'Alphington',
    'Altona',
    'Anstey',
    'Armadale',
    'Ascot Vale',
    'Ashburton',
    'Aspendale',
    'Auburn',
    'Balaclava',
    'Batman',
    'Baxter',
    'Bayswater',
    'Beaconsfield',
    'Belgrave',
    'Bell',
    'Bentleigh',
    'Berwick',
    'Bittern',
    'Blackburn',
    'Bonbeach',
    'Boronia',
    'Box Hill',
    'Brighton Beach',
    'Broadmeadows',
    'Brunswick',
    'Burnley',
    'Burwood',
    'Camberwell',
    'Canterbury',
    'Cardinia Road',
    'Carnegie',
    'Carrum',
    'Caufield',
    'Chatham',
    'Chelsea',
    'Cheltenham',
    'Clifton Hill',
    'Coburg',
    'Collingwood',
    'Coolaroo',
    'Craigieburn',
    'Cranbourne',
    'Crib Point',
    'Croxton',
    'Croydon',
    'Dandenong',
    'Darebin',
    'Darling',
    'Dennis',
    'Diamond Creek',
    'Diggers Rest',
    'Eaglemont',
    'East Camberwell',
    'East Malvern',
    'East Pakenham',
    'East Richmond',
    'Edithvale',
    'Elsternwick',
    'Eltham',
    'Epping',
    'Essendon',
    'Fairfield',
    'Fawkner',
    'Ferntree Gully',
    'Flagstaff',
    'Flemington Bridge',
    'Flemington Racecourse',
    'Flinders Street',
    'Footscray',
    'Frankston',
    'Gardenvale',
    'Gardiner',
    'Ginifer',
    'Glen Huntly',
    'Glen Iris',
    'Glen Waverley',
    'Glenbervie',
    'Glenferrie',
    'Glenroy',
    'Gowrie',
    'Greensborough',
    'Hallam',
    'Hampton',
    'Hartwell',
    'Hastings',
    'Hawksburn',
    'Hawkstowe',
    'Hawthorn',
    'Heatherdale',
    'Heathmont',
    'Heidelberg',
    'Heyington',
    'Highett',
    'Holmesglen',
    'Hoppers Crossing',
    'Hughesdale',
    'Huntingdale',
    'Hurstbridge',
    'Ivanhoe',
    'Jacana',
    'Jewell',
    'Jolimont',
    'Jordanville',
    'Kananook',
    'Keilor Plains',
    'Kensington',
    'Keon Park',
    'Kooyong',
    'Laburnum',
    'Lalor',
    'Laverton',
    'Leawarra',
    'Lilydale',
    'Lynbrook',
    'Macaulay',
    'Macleod',
    'Malvern',
    'McKinnon',
    'Melbourne Central',
    'Mentone',
    'Merinda Park',
    'Merlynston',
    'Mernda',
    'Merri',
    'Middle Brighton',
    'Middle Footscray',
    'Middle Gorge',
    'Mitcham',
    'Montmorency',
    'Moonee Ponds',
    'Moorabbin',
    'Mooroolbark',
    'Mordialloc',
    'Moreland',
    'Morradoo',
    'Mount Waverley',
    'Murrambeena',
    'Narre Warren',
    'Newmarket',
    'Newport',
    'Noble Park',
    'North Brighton',
    'North Melbourne',
    'North Richmond',
    'North Williamstown',
    'Northcote',
    'Nunawading',
    'Oak Park',
    'Oakleigh',
    'Officer',
    'Ormond',
    'Pakenham',
    'Parkdale',
    'Parliament',
    'Pascoe Vale',
    'Patterson',
    'Prahran',
    'Preston',
    'Regent',
    'Reservoir',
    'Richmond',
    'Ringwood',
    'Ringwood East',
    'Ripponlea',
    'Riversdale',
    'Rosanna',
    'Roxburgh Park',
    'Royal Park',
    'Rushall',
    'Ruthven',
    'Sandown Park',
    'Sandringham',
    'Seaford',
    'Seaholme',
    'Seddon',
    'Showgrounds',
    'Somerville',
    'South Kensington',
    'South Morang',
    'South Yarra',
    'Southern Cross',
    'Southland',
    'Spotswood',
    'Springvale',
    'St Albans',
    'Stony Point',
    'Strathmore',
    'Sunbury',
    'Sunshine',
    'Syndal',
    'Tecoma',
    'Thomastown',
    'Thornbury',
    'Toorak',
    'Tooronga',
    'Tottenham',
    'Tyabb',
    'Union',
    'Upfield',
    'Upper Ferntree Gully',
    'Upwey',
    'Victoria Park',
    'Watergardens',
    'Watsonia',
    'Wattle Glen',
    'Werribee',
    'West Footscray',
    'West Richmond',
    'Westall',
    'Westgarth',
    'Westona',
    'Williams Landing',
    'Williamstown',
    'Williamstown Beach',
    'Willison',
    'Windsor',
    'Yarraman',
    'Yarraville',
]
